export const GET_SEARCH_RESPONSE = 'GET_SEARCH_RESPONSE';

export const ADD_NEW_COURSE_RESPONSE = 'ADD_NEW_COURSE_RESPONSE';
export const UPDATE_EXISTING_COURSE_RESPONSE = 'UPDATE_EXISTING_COURSE_RESPONSE';
export const DELETE_COURSE_RESPONSE = 'DELETE_COURSE_RESPONSE';

export const GET_AUTHORS_RESPONSE = 'GET_AUTHORS_RESPONSE';

export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_ERROR = 'API_CALL_ERROR';
